### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/semantic-search#23]
- Branch: master
- Build command: `docker build -t semantic-search .`

```sh
Sending build context to Docker daemon  1.804MB
Step 1/4 : FROM tiangolo/python-machine-learning:cuda9.1-python3.7
...

  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/conda/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-a74vq7au/orjson/setup.py
```

**Comment by jvwong** [comment]
@JohnGiorgi any clue what's going on here?

**Comment by JohnGiorgi** [comment]
@jvwong I think I have fixed it. I will open a PR
